import { Sparkles } from 'lucide-react';

export default function SearchContext({ context, query }) {
    if (!context) return null;

    return (
        <div className="mb-10 rounded-2xl border-2 border-indigo-400 dark:border-indigo-600 bg-gradient-to-br from-indigo-50 to-white dark:from-indigo-900/40 dark:to-slate-900 p-8 animate-fade-in shadow-lg relative overflow-hidden">
            {/* Background decorative blob */}
            <div className="absolute -top-24 -right-24 h-64 w-64 rounded-full bg-indigo-500/10 blur-3xl pointer-events-none" />

            <div className="relative flex items-start gap-5">
                <div className="rounded-xl bg-gradient-to-b from-indigo-500 to-indigo-700 p-3.5 text-white shadow-lg shadow-indigo-600/30">
                    <Sparkles className="h-7 w-7" />
                </div>
                <div className="space-y-4 flex-1">
                    <div className="flex items-center justify-between">
                        <h3 className="font-black text-slate-900 dark:text-white text-2xl tracking-tight">
                            AI Insights
                        </h3>
                        <span className="shrink-0 rounded-full bg-indigo-100 dark:bg-indigo-900/50 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-indigo-700 dark:text-indigo-400 border border-indigo-200 dark:border-indigo-800">
                            Generated by AI Agent
                        </span>
                    </div>
                    <div className="text-slate-800 dark:text-slate-200 leading-relaxed text-lg font-medium pr-8">
                        {context}
                    </div>
                </div>
            </div>
        </div>
    );
}
