import { Zap } from 'lucide-react';

export default function SearchContext({ context, query }) {
    if (!context) return null;

    return (
        <div className="mb-8 rounded-2xl border border-indigo-200 dark:border-indigo-800 bg-indigo-50 dark:bg-indigo-900/30 p-6 animate-fade-in shadow-sm">
            <div className="flex items-start gap-4">
                <div className="rounded-xl bg-indigo-600 dark:bg-indigo-500 p-3 text-white shadow-md shadow-indigo-600/20">
                    <Zap className="h-6 w-6" />
                </div>
                <div className="space-y-3 flex-1">
                    <div className="flex items-center justify-between">
                        <h3 className="font-bold text-slate-900 dark:text-white text-lg tracking-tight">
                            AI Context for <span className="text-indigo-600 dark:text-indigo-400">"{query}"</span>
                        </h3>
                        <span className="shrink-0 rounded-full bg-indigo-100 dark:bg-indigo-900/50 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-indigo-600 dark:text-indigo-400">
                            AI General Knowledge
                        </span>
                    </div>
                    <p className="text-slate-700 dark:text-slate-300 leading-relaxed text-base">
                        {context}
                    </p>
                    <div className="pt-2 flex items-center gap-2 text-xs font-medium text-slate-400 dark:text-slate-500">
                        <span>•</span>
                        <span>Generated by AI Agent</span>
                        <span>•</span>
                        <span>Independent of your documents</span>
                    </div>
                </div>
            </div>
        </div>
    );
}
